### ISSUE TITLE
Non-standard `searchParams.set()` method in share button tutorial?

### ISSUE THREAD

**Issue by rizkysyazuli** [ember-learn/super-rentals-tutorial#139]
I was reading the [share button](https://guides.emberjs.com/release/tutorial/part-2/service-injection/) tutorial when i saw the `URL` browser API. I'm not familiar with this. So i look it up on MDN and found the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/URL). But i noticed that the `searchParams` property is actually read only. Which means it shouldn't have a `set()` method. Yet it works.

Is this a mistake on the MDN side?

**EDIT**: after looking around some more, i found the `URLSearchParams` API on MDN. This one does actually have a `get()` and `set()` method.

**Comment by locks** [comment]
(tranferred the issue since it is about super rentals tutorial content)

As you note, `URL#searchParams` returns an instance of `URLSearchParams`, so everything matches up! You can't reassign the `searchParams` property to something else, but you can use the `set` API it provides to update it!
Can you open a PR with a suggestion to clarify this? Maybe a sentence saying where to find the documentation for `URL` and `URLSearchParams`?

**Comment by rizkysyazuli** [comment]
Sure.. will do. Should i do like a "Zoey says.." thing? 😄

**Comment by chancancode** [comment]
IMO, the URL/searchParams API isn't really the focus of this part. For most beginners, I think this may just be something they copy and paste and not something that they give too much thought to, which is okay, since the ultimate learning objective here is about the service. Giving it a lot of text may be distracting those readers, making it feel like it's something they must stop and understand before moving forward. I think a good compromise will be adding the MDN links to the keywords, something like this:

```md
Conveniently, the browser provides a handy [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) class that handles escaping and joining of [query params](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set) for us.
```

What do you think?

**Comment by rizkysyazuli** [comment]
Sure. As a reader.. that works for me.

**Comment by chancancode** [comment]
@rizkysyazuli still interested in making the change?

**Comment by joshuabremerdexcom** [comment]
I was looking for some "help-needed" tasks and this issue seems like it's not an actual problem. [searchParams](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) *is* a readonly property, but we're not actually editing that property. We're using the setter, that comes with that object. 

I think adding a "Zoey says..." would just distract from the instruction content, especially given that the code works, and actually reads really well.

I know it's 2 years old, but I'd like to propose that this be closed.

**Comment by chancancode** [comment]
Yes, the link to MDN was added in #167 so this can be closed now, thanks everyone!
